### ISSUE TITLE
not wrok on Android

### ISSUE THREAD

**Issue by DLTech21** [rillian/tiff2png#2]
use on Andoird, while coverting tiff to png,  it falls 

```
TIFFReadScanline(tif, tiffline, row, 0) < 0
```

**Comment by rillian** [comment]
That suggests the data you're passing isn't supported by libtiff, or possibly that something is miscompiled. Without more information it's difficult to say what might be wrong.

**Comment by DLTech21** [comment]
the same data passing on Mac or webassembly both work, that was wried.... I think  libtiff built by ndk was miscompiled. Have you built libtiff by ndk before?

**Comment by rillian** [comment]
I have not, sorry. Maybe [this](https://github.com/leleliu008/ndk-pkg-formula-repository/blob/master/formula/libtiff.sh) is helpful?

**Comment by DLTech21** [comment]
I have try ndk-pkg yet, not run ok with your code unlucky... May be this code not test successful on Android

**Comment by DLTech21** [comment]
I found this image can not convert on Android, can you fix it, if you need ndk static library , I can send that...Thank you
[image_86.tif.zip](https://github.com/rillian/tiff2png/files/7833526/image_86.tif.zip)
